### ISSUE TITLE
Redirect URI mismatch 

### ISSUE THREAD

**Issue by shinichimg** [Kentico/xperience-google-searchconsole#1]
### Brief bug description

After following the steps in the tutorial, I got the error "Server Error in '/' Application".  And request URL seems to remove my domain. How can I fix this issue? Thanks. 

### Screenshots
![Screenshot 2022-10-26 170803](https://user-images.githubusercontent.com/37854342/197999666-226d25c9-bb00-4af4-8ed4-7070b798dcc2.png)

**Comment by kentico-ericd** [comment]
Hello! Please make sure the "Authorized redirect URIs" is accurate based on how you are hosting your CMS application. For example, if you access the administration UI from https://localhost/admin, you need to include _/admin_ in the redirect URI.

Also, I don't believe you can use _localhost_, as the website needs to be [registered as a property](https://support.google.com/webmasters/answer/34592) in Google Search Console. If you would just like to test the integration locally, you can set up a temporary [ngrok](https://ngrok.com/) tunnel.

**Comment by shinichimg** [comment]
Oh! Thanks, It's worked perfectly after I changed localhost to  my top-level domain which hosted in Azure.
